### ISSUE TITLE
todo example counter error

### ISSUE THREAD

**Issue by mattkrick** [delta-db/deltadb#26]
when a 2nd user makes a change, the counter loses sync.
Repro steps:
check a todo 
in a 2nd browser, check another todo
the first window has lost sync

**Comment by redgeoff** [comment]
Thanks for the report, Matt! I tried to duplicate the issue with Chrome, Firefox and Safari and wasn't able to duplicate it. Could you please provide more details, including the browser you were using?

**Comment by mattkrick** [comment]
well that's really weird. I used chrome as the first browser & chrome canary as the second. on OSX

**Comment by redgeoff** [comment]
Hmm... so does that mean that you can't duplicate it any more? If you can, can you describe what you mean by it _lost sync_? Did it just stop communicating entirely? There is a retry mechanism that is defaulted to kick in after 3 mins.

**Comment by mattkrick** [comment]
oh it's still there, in fact the initial load returns a false count (always lower than actual)

**Comment by redgeoff** [comment]
Oh, I see it now. I'll look into it. Thanks!

**Comment by redgeoff** [comment]
Fixed by https://github.com/delta-db/deltadb/pull/29. Thanks, Matt!
